global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'monad_rpc'
    metrics_path: /metrics
    static_configs:
      - targets: ['${MONAD_RPC_HOST:127.0.0.1}:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['127.0.0.1:9100']
